config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'static_pages#home'

  get 'inicio' => 'static_pages#home', as: :home
  get 'contato' => 'static_pages#contact', as: :contact
  get 'noticias' => 'posts#index', as: :posts
  get 'noticias/:slug' => 'posts#show', as: :post
  get 'decisoes' => 'judgements#index', as: :judgements
  get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  get 'sobre' => 'static_pages#about', as: :about

  scope path: 'cartilhas-e-manuais' do
    get 'consumidor' => 'static_pages#consumer_content', as: :consumer_content
    get 'construtoras' => 'static_pages#construction_content', as: :construction_content
    get 'previdenciario' => 'static_pages#social_security_content', as: :social_security_content
    get 'sfh-sfi' => 'static_pages#sfh_sfi_content', as: :sfh_sfi_content
  end

  resources :newsletter_subscribers, only: %i[create]

  namespace 'admin' do
    root to: 'posts#index'

    resources :judgements, path: :decisoes
    resources :posts, path: :noticias
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  POST_COUNT = 3

  def home
    @posts = Post.published.sorted_by_date(:desc).limit(POST_COUNT)
  end

  def about; end

  def contact; end

  def consumer_content; end

  def construction_content; end

  def sfh_sfi_content; end

  def social_security_content; end
end

app/views/static_pages/about.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <!-- Hero section -->
  <div class="mt-10 mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0">
      <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
        Em defesa dos consumidores desde <span class="font-extrabold">2001</span>
      </h1>
      <p class="relative mt-6 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
        O IBEDEC trabalha diariamente no atendimento às mais diversas reclamações e dúvidas dos consumidores, orientando−os na luta pelo conhecimento e respeito aos seus direitos.
      </p>
    </div>
  </div>

  <!-- Mission -->
  <div class="mx-auto mt-16 max-w-7xl px-6 lg:px-8">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
      Nossa missão
    </h2>
    <div class="mt-6 flex flex-col gap-y-20 gap-x-8 lg:flex-row">
      <div class="space-y-6 lg:w-full lg:max-w-2xl lg:flex-auto">
        <p class="text-xl leading-8 text-gray-600 text-justify">
          O IBEDEC tem por objetivo reunir cientistas das áreas econômicas e jurídicas para estudar e orientar a população em geral sobre as relações de consumo e todos os seus desdobramentos, visando difundir os direitos dos consumidores e a forma de defendê-los.
        </p>
        <p class="text-xl leading-8 text-gray-600 text-justify">
          Tem por objetivo ainda, lutar junto aos três Poderes da República Federativa do Brasil (Legislativo, Executivo e Judiciário) para que os direitos dos consumidores, garantidos pela Constituição Federal, Código Civil, Código de Defesa do Consumidor e Legislação Específica, sejam respeitados.
        </p>
        <p class="text-xl leading-8 text-gray-600 text-justify">
          Tem por objetivo maior, lutar por um <span class="font-bold text-gray-900">país mais justo</span>.
        </p>
      </div>
      <div class="lg:flex lg:flex-auto lg:justify-center">
        <dl class="space-y-8 xl:w-80">
          <div class="flex items-center flex-col-reverse gap-y-2 lg:items-start">
            <dt class="text-base leading-7 text-gray-600">anos na luta pelos consumidores</dt>
            <dd class="text-5xl font-semibold tracking-tight text-gray-900"><%= years_since_inauguration %></dd>
          </div>
          <div class="flex items-center flex-col-reverse gap-y-2 lg:items-start">
            <dt class="text-base leading-7 text-gray-600">unidades por todo o Brasil</dt>
            <dd class="text-5xl font-semibold tracking-tight text-gray-900">5</dd>
          </div>
        </dl>
      </div>
    </div>
  </div>

  <!-- Images -->
  <div class="grid grid-cols-1 gap-8 justify-items-center mx-auto mt-24 max-w-7xl px-6 sm:grid-cols-2 md:grid-cols-3 lg:px-8">
    <%= link_to vite_asset_path('images/about/meeting-1.png'), target: '_blank' do %>
      <%= vite_image_tag 'images/about/meeting-1.png', class: 'h-5/6 w-full object-cover rounded-lg bg-gray-900/5 shadow-lg' %>
    <% end %>
    <%= link_to vite_asset_path('images/about/meeting-2.png'), target: '_blank' do %>
      <%= vite_image_tag 'images/about/meeting-2.png', class: 'h-5/6 w-full object-cover rounded-lg bg-gray-900/5 shadow-lg' %>
    <% end %>
    <%= link_to vite_asset_path('images/about/meeting-3.png'), target: '_blank' do %>
      <%= vite_image_tag 'images/about/meeting-3.png', class: 'h-5/6 w-full object-cover rounded-lg bg-gray-900/5 shadow-lg' %>
    <% end %>
  </div>
</div>

app/views/static_pages/construction_content.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <div class="mt-10 mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto grid max-w-2xl grid-cols-1 items-start gap-x-16 gap-y-8 lg:max-w-none lg:grid-cols-2">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
          Construtoras
        </h1>
        <h3 class="mt-10 text-xl font-medium tracking-tight text-gray-600 sm:text-3xl">
          Cartilhas
        </h3>
        <p class="relative mt-4 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          Devido ao crescente número de ações contra construtoras, o IBEDEC lançou uma edição especial da Cartilha do Consumidor onde o tema principal são as construtoras
        </p>
        <p class="relative mt-4 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          A reprodução parcial ou total é permitida <strong>desde que citada a fonte</strong>.
        </p>
      </div>
      <div>
        <ul role="list" class="space-y-3">
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Construtoras (2021)', '../cartilhas/Cartilha_Construtoras_2021.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Construtoras (2015)', '../cartilhas/Cartilha_Construtoras_2015.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/consumer_content.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <div class="mt-10 mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto grid max-w-2xl grid-cols-1 items-start gap-x-16 gap-y-8 lg:max-w-none lg:grid-cols-2">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
          Consumidor
        </h1>
        <h3 class="mt-10 text-xl font-medium tracking-tight text-gray-600 sm:text-3xl">
          Cartilhas e manuais
        </h3>
        <p class="relative mt-4 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          As cartilhas e manuais abordam diferentes temas, como compras online, direitos do consumidor no transporte aéreo, problemas com planos de saúde, entre outros.
        </p>
        <p class="relative mt-4 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          Cada material traz informações claras e objetivas, além de dicas práticas para que os consumidores possam evitar problemas e buscar soluções quando necessário.
        </p>
        <p class="relative mt-4 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          A reprodução parcial ou total é permitida <strong>desde que citada a fonte</strong>.
        </p>
      </div>
      <div>
        <ul role="list" class="space-y-3">
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor', '../cartilhas/Cartilha_do_Consumidor_2_Edicao.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Condômino-Síndico', '../cartilhas/Cartilha_Condomino_Sindico.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Construtoras', '../cartilhas/Cartilha_Construtoras_2015.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Fornecedor', '../cartilhas/Cartilha_do_Consumidor_Edicao_Especial_Fornecedor_1_Edicao.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Idoso', '../cartilhas/Cartilha_Idoso_4a_edicao.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Turismo', '../cartilhas/Cartilha_do_Consumidor_Edicao_Especial_Turismo.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Endividados', '../cartilhas/Cartilha_do_Consumidor_1_Edicao_Endividados.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Veículos', '../cartilhas/Cartilha_Veiculos_2_Edicao.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Manual Olho Vivo Consumidor', '../manuais/Manual_Olho_Vivo_Consumidor_Goiania.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% content_for(:head_tags) do %>
  <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
  <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<% end %>

<div class="pb-16 pt-24 sm:pt-32">
  <div class="mx-auto max-w-7xl mt-10 px-6 lg:px-8">
    <div class="mx-auto lg:mx-0">
      <h1 class="max-w-2xl text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
        Fale com a gente
      </h1>
      <div class="grid grid-cols-1 mt-6">
        <p class="text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          No IBEDEC, você encontra orientações sobre assuntos como <strong>direitos do consumidor</strong>, <strong>distrato</strong>, <strong>vícios de construção</strong>, <strong>construtoras</strong>, <strong>rescisão de contratos</strong>, <strong>financiamento imobiliário</strong>, <strong>atraso na entrega</strong>, <strong>multas contratuais</strong>, <strong>juros de obra</strong>, <strong>compra e venda de imóveis</strong>, <strong>agentes financeiros</strong> e a <strong>Caixa Econômica Federal</strong>.
        </p>
        <p class="text-xl leading-8 mt-4 text-gray-600 max-w-4xl text-justify">
          O IBEDEC está presente em diferentes localidades mas você também pode agendar uma vídeo chamada conosco. Entre em contato com uma de nossas unidades abaixo e agende seu atendimento.
        </p>
      </div>
    </div>
    <div class="mx-auto mt-16 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:col-span-2 lg:gap-8">
      <div class="rounded-2xl bg-gray-50 p-10">
        <%= link_to 'Brasília - DF', 'https://goo.gl/maps/LrfvX33iKP8jz6XDA', target: '_blank', class: 'text-base font-semibold leading-7 text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
        <address class="mt-3 space-y-1 text-sm not-italic leading-6 text-gray-600">
          <p>Venâncio Shopping, Asa Sul</p>
          <p>Sala 217, 2º piso, em frente ao PROCON</p>
        </address>
        <dl class="mt-3 space-y-1 text-sm leading-6 text-gray-600">
          <div>
            <dt class="sr-only">Email</dt>
            <dd>
              <a class="font-semibold text-ibedec-blue-600 hover:text-ibedec-blue-100" href="mailto:atendimento@ibedec.org.br?subject=Contato via site">
                atendimento@ibedec.org.br
              </a>
            </dd>
          </div>
          <div class="mt-1">
            <dt class="sr-only">Telefone</dt>
            <dd>(61) 3345-2492</dd>
            <div class="flex items-center space-x-1">
              <%= link_to '(61) 99278-0848', 'https://wa.me/5561992780848', class: 'font-medium text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
              <%= svg_icon(name: 'whatsapp', css_class: 'h-6 w-6 text-whatsapp-green-500 mb-0.5') %>
            </div>
            <div class="flex items-center space-x-1">
              <%= link_to '(61) 99277-1092', 'https://wa.me/5561992771092', class: 'font-medium text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
              <%= svg_icon(name: 'whatsapp', css_class: 'h-6 w-6 text-whatsapp-green-500 mb-0.5') %>
            </div>
          </div>
        </dl>
      </div>
      <div class="rounded-2xl bg-gray-50 p-10">
        <%= link_to 'Belo Horizonte - MG', 'https://goo.gl/maps/GL3pNn56WZr71Qoj6', target: '_blank', class: 'text-base font-semibold leading-7 text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
        <address class="mt-3 space-y-1 text-sm not-italic leading-6 text-gray-600">
          <p>Rua Martim de Carvalho, 671, Bairro Santo Agostinho</p>
          <p>CEP 30190-094</p>
        </address>
        <dl class="mt-3 space-y-1 text-sm leading-6 text-gray-600">
          <div>
            <dt class="sr-only">Email</dt>
            <dd>
              <a class="font-semibold text-ibedec-blue-600 hover:text-ibedec-blue-100" href="mailto:atendimentomg@ibedec.org.br?subject=Contato via site">
                atendimentomg@ibedec.org.br
              </a>
            </dd>
          </div>
          <div class="mt-1">
            <dt class="sr-only">Telefone</dt>
            <dd>(31) 3337-8815</dd>
            <div class="flex items-center space-x-1">
              <%= link_to '(31) 3337-8846', 'https://wa.me/553133378846', class: 'font-medium text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
              <%= svg_icon(name: 'whatsapp', css_class: 'h-6 w-6 text-whatsapp-green-500 mb-0.5') %>
            </div>
          </div>
        </dl>
      </div>
      <div class="rounded-2xl bg-gray-50 p-10">
        <%= link_to 'Campo Grande - MS', 'https://goo.gl/maps/A28X3z7iEpN5UabV6', target: '_blank', class: 'text-base font-semibold leading-7 text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
        <address class="mt-3 space-y-1 text-sm not-italic leading-6 text-gray-600">
          <p>Rua da Lira, 234, Vila Carlota</p>
          <p>CEP 79051-550</p>
        </address>
        <dl class="mt-3 space-y-1 text-sm leading-6 text-gray-600">
          <div>
            <dt class="sr-only">Email</dt>
            <dd>
              <a class="font-semibold text-ibedec-blue-600 hover:text-ibedec-blue-100" href="mailto:atendimentoms@ibedec.org.br?subject=Contato via site">
                atendimentoms@ibedec.org.br
              </a>
            </dd>
          </div>
          <div class="mt-1">
            <dt class="sr-only">Telefone</dt>
            <dd>(67) 3015-1090</dd>
            <dd>(67) 99240-4247</dd>
          </div>
        </dl>
      </div>
      <div class="rounded-2xl bg-gray-50 p-10">
        <%= link_to 'Goiânia - GO', 'https://goo.gl/maps/g3aCyKj7fVRn1MRNA', target: '_blank', class: 'text-base font-semibold leading-7 text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
        <address class="mt-3 space-y-1 text-sm not-italic leading-6 text-gray-600">
          <p>Avenida São Carlos, 179, Jardim Planalto</p>
          <p>Quadra 27, lote 2, CEP 74333-020</p>
        </address>
        <dl class="mt-3 space-y-1 text-sm leading-6 text-gray-600">
          <div>
            <dt class="sr-only">Email</dt>
            <dd>
              <a class="font-semibold text-ibedec-blue-600 hover:text-ibedec-blue-100" href="mailto:atendimentogo@ibedec.org.br?subject=Contato via site">
                atendimentogo@ibedec.org.br
              </a>
            </dd>
          </div>
          <div class="mt-1">
            <dt class="sr-only">Telefone</dt>
            <div class="flex items-center space-x-1">
              <%= link_to '(62) 3215-7777', 'https://wa.me/556232157777', class: 'font-medium text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
              <%= svg_icon(name: 'whatsapp', css_class: 'h-6 w-6 text-whatsapp-green-500 mb-0.5') %>
            </div>
            <div class="flex items-center space-x-1">
              <%= link_to '(62) 99973-9305', 'https://wa.me/5562999739305', class: 'font-medium text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
              <%= svg_icon(name: 'whatsapp', css_class: 'h-6 w-6 text-whatsapp-green-500 mb-0.5') %>
            </div>
          </div>
        </dl>
      </div>
      <div class="rounded-2xl bg-gray-50 p-10">
        <%= link_to 'São Luís - MA', 'https://goo.gl/maps/q6p7GGzhX7fsEeFDA', target: '_blank', class: 'text-base font-semibold leading-7 text-ibedec-blue-600 hover:text-ibedec-blue-100' %>
        <address class="mt-3 space-y-1 text-sm not-italic leading-6 text-gray-600">
          <p>Avenida dos Holandeses, 9, Ponta D‘Areia</p>
          <p>Edifício Tech Office, Sala 904, torre 02, CEP 65065-180</p>
        </address>
        <dl class="mt-3 space-y-1 text-sm leading-6 text-gray-600">
          <div>
            <dt class="sr-only">Email</dt>
            <dd>
              <a class="font-semibold text-ibedec-blue-600 hover:text-ibedec-blue-100" href="mailto:atendimentoma@ibedec.org.br?subject=Contato via site">
                atendimentoma@ibedec.org.br
              </a>
            </dd>
          </div>
          <div class="mt-1">
            <dt class="sr-only">Telefone</dt>
            <dd>(98) 3227-2965</dd>
          </div>
        </dl>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% content_for(:head_tags) do %>
  <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
  <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<% end %>

<div class="flex flex-col min-h-screen relative isolate px-6 pt-28 pb-16 bg-gradient-to-r from-ibedec-blue-50 to-ibedec-yellow-50 lg:px-8 lg:pt-36">
  <div class="mt-10 max-w-4xl sm:m-auto">
    <div class="text-center">
      <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
        Instituto Brasileiro de Estudo e Defesa das Relações de Consumo
      </h1>
      <p class="mt-6 text-2xl leading-8 text-gray-500">
        O IBEDEC atua, sem fins lucrativos, na defesa do direito do consumidor.
      </p>
      <div class="flex flex-col gap-x-6 mt-10 sm:flex-row sm:items-center sm:justify-center">
        <%= link_to 'Fale com a gente', contact_path, class: 'rounded-md bg-ibedec-blue-100 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-ibedec-blue-400 hover:text-ibedec-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ibedec-blue-600', data: { action: 'click->calendly#openModal' } %>
      </div>
    </div>
  </div>
  <div class="absolute bottom-4 left-1/2 transform -translate-x-1/2 animate-bounce-slow">
    <%= svg_icon(name: 'chevron-down', css_class: 'h-7 w-7') %>
  </div>
</div>

<div class="py-12 sm:py-20">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0">
      <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
        Últimas notícias
      </h2>
      <p class="mt-2 text-lg leading-8 text-gray-600">
        Fique por dentro das atualizações mais importantes do mundo do consumidor.
      </p>
    </div>
    <div class="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-x-16 gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
      <% @posts.each do |post| %>
        <% post_presenter = PostPresenter.new(post) %>
        <article class="flex flex-col items-start">
          <div class="relative w-full">
            <%= link_to post_path(post.slug) do %>
              <%= image_tag(url_for(post.cover_image), class: 'aspect-[16/9] w-full rounded-2xl bg-gray-100 object-cover sm:aspect-[2/1] lg:aspect-[3/2]') %>
            <% end %>
          </div>
          <%= link_to post_path(post.slug), class: 'w-full' do %>
            <div class="mt-8 flex items-center gap-x-4 text-xs">
              <time datetime="2020-03-16" class="text-gray-500">
                <%= l(post.published_at.to_date, format: :long) %>
              </time>
            </div>
            <div class="group relative">
              <h3 class="mt-3 text-lg font-semibold leading-6 text-gray-900 group-hover:text-gray-600">
                <span class="absolute inset-0"></span>
                <%= post.title %>
              </h3>
              <p class="mt-5 line-clamp-3 text-sm leading-6 text-gray-600">
                <%= post_presenter.body_text.truncate(120) %>
              </p>
            </div>
          <% end %>
        </article>
      <% end %>
    </div>
    <div class="flex justify-end mt-10">
      <%= link_to posts_path, class: 'font-semibold leading-7 text-ibedec-blue-500 hover:text-ibedec-blue-100' do %>
        Leia mais notícias <span aria-hidden="true"> &rarr;</span>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/sfh_sfi_content.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <div class="mt-10 mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto grid max-w-2xl grid-cols-1 items-start gap-x-16 gap-y-8 lg:max-w-none lg:grid-cols-2">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
          SFH e SFI
        </h1>
        <h3 class="mt-10 text-xl font-medium tracking-tight text-gray-600 sm:text-3xl">
          Cartilhas
        </h3>
        <p class="relative mt-4 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          Tudo que você sempre quis saber sobre o financiamento da casa própria, mas nunca ninguém lhe explicou. Este é o conteúdo que você irá encontrar na Cartilha do Mutuário, material criado pelo IBEDEC para a <%= link_to 'ABMH', 'https://abmhgo.org.br' %> e que serve de guia de direitos a todos os mutuários do SFH, para que possam defender-se dos abusos dos agentes financeiros.
        </p>
        <p class="relative mt-4 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
          A reprodução parcial ou total é permitida <strong>desde que citada a fonte</strong>.
        </p>
      </div>
      <div>
        <ul role="list" class="space-y-3">
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Mutuário - 4ª Edição', '../cartilhas/Cartilha_Mutuario_4a_Edicao.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Cartilha do Consumidor - Edição Especial: Construtoras', '../cartilhas/Cartilha_Construtoras_2015.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
          <li class="overflow-hidden rounded-md border border-gray-50 bg-white px-6 py-4 shadow-md">
            <%= link_to 'Manual da Casa Própria - 2ª Edição', '../manuais/Manual_da_Casa_Propria_2_Edicao.pdf', target: '_blank', class: 'text-ibedec-blue-300 font-semibold hover:text-ibedec-blue-600' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>