config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'static_pages#home'

  get 'inicio' => 'static_pages#home', as: :home
  get 'contato' => 'static_pages#contact', as: :contact
  get 'noticias' => 'posts#index', as: :posts
  get 'noticias/:slug' => 'posts#show', as: :post
  get 'decisoes' => 'judgements#index', as: :judgements
  get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  get 'sobre' => 'static_pages#about', as: :about

  scope path: 'cartilhas-e-manuais' do
    get 'consumidor' => 'static_pages#consumer_content', as: :consumer_content
    get 'construtoras' => 'static_pages#construction_content', as: :construction_content
    get 'previdenciario' => 'static_pages#social_security_content', as: :social_security_content
    get 'sfh-sfi' => 'static_pages#sfh_sfi_content', as: :sfh_sfi_content
  end

  resources :newsletter_subscribers, only: %i[create]

  namespace 'admin' do
    root to: 'posts#index'

    resources :judgements, path: :decisoes
    resources :posts, path: :noticias
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  VALID_SORT_ORDERS = %i[asc desc].freeze

  belongs_to :user
  has_one_attached :cover_image

  before_save :set_slug

  validates :title, :published_at, :cover_image, presence: true
  validate :body_has_text

  scope :published, -> { where.not(published_at: nil) }
  scope :sorted_by_date, lambda { |order|
    order = VALID_SORT_ORDERS.find { |sort_order| sort_order.downcase.to_sym == order }

    order("posts.published_at #{order}")
  }

  private

  def set_slug
    self.slug = title.parameterize
  end

  def body_has_text
    errors.add(:body, :blank) if Nokogiri::HTML(body).text.blank?
  end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  class PostsController < ApplicationController
    load_and_authorize_resource

    def index
      @posts = Post.accessible_by(current_ability).sorted_by_date(:desc).page(params[:page])
    end

    def create
      @post.user = current_user

      if @post.save
        redirect_to admin_posts_path, success: 'Notícia criada com sucesso'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @post.update(post_params)
        redirect_to admin_posts_path, success: 'Notícia atualizada com sucesso'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy

      redirect_to admin_posts_path, success: 'Notícia apagada com sucesso', status: :see_other
    end

    private

    def post_params
      params.require(:post).permit(:title, :body, :published_at, :cover_image)
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  POSTS_PER_PAGE = 6

  before_action :set_post, only: %i[show]

  def index
    @posts = Post.published.sorted_by_date(:desc).page(params[:page]).per(POSTS_PER_PAGE)
  end

  def show; end

  private

  def set_post
    @post = Post.published.find_by!(slug: params[:slug])
  end
end

app/views/posts/index.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <!-- Hero section -->
  <div class="mx-auto max-w-7xl mt-10 px-6 lg:px-8">
    <div class="mx-auto max-w-3xl lg:mx-0">
      <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
        Últimas notícias
      </h1>
      <p class="relative mt-6 text-xl leading-8 text-gray-600 max-w-4xl text-justify">
        Fique por dentro das novidades sobre os direitos do consumidor e acompanhe o trabalho do IBEDEC na defesa dos seus interesses.
      </p>
    </div>
  </div>

  <!-- Content -->
  <div class="mx-auto mt-16 max-w-7xl px-6 lg:px-8">
    <div class="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-x-16 gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
      <% if @posts.any? %>
        <% @posts.each do |post| %>
          <% post_presenter = PostPresenter.new(post) %>
          <article class="flex flex-col items-start">
            <div class="relative w-full">
              <%= link_to post_path(post.slug) do %>
                <%= image_tag(url_for(post.cover_image), class: 'aspect-[16/9] w-full rounded-2xl bg-gray-100 object-cover sm:aspect-[2/1] lg:aspect-[3/2]') %>
              <% end %>
            </div>
            <%= link_to post_path(post.slug), class: 'w-full' do %>
              <div class="mt-8 flex items-center gap-x-4 text-xs">
                <time datetime="2020-03-16" class="text-gray-500">
                  <%= l(post.published_at.to_date, format: :long) %>
                </time>
              </div>
              <div class="group relative">
                <h3 class="mt-3 text-lg font-semibold leading-6 text-gray-900 group-hover:text-gray-600">
                  <span class="absolute inset-0"></span>
                  <%= post.title %>
                </h3>
                <p class="mt-5 line-clamp-3 text-sm leading-6 text-gray-600">
                  <%= post_presenter.body_text.truncate(120) %>
                </p>
              </div>
            <% end %>
          </article>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @posts.any? %>
    <%= paginate @posts %>
  <% end %>
</div>

app/views/posts/show.html.erb
<% post_presenter = PostPresenter.new(@post) %>

<% content_for(:head_tags) do %>
  <meta property="og:url" content="<%= post_url(@post.slug) %>" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="<%= @post.title %>" />
  <meta property="og:description" content="<%= post_presenter.body_text.truncate(160) %>" />
  <meta property="og:image" content="<%= rails_blob_url(@post.cover_image) %>" />
<% end %>

<div class="pb-16 pt-24 sm:pt-32">
  <div class="mt-10 mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto grid max-w-2xl grid-cols-1 items-start gap-x-8 gap-y-8 sm:gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-2">
      <div class="order-2 lg:order-1">
        <div class="text-base leading-7 text-gray-700 lg:max-w-lg">
          <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
            <%= @post.title %>
          </h1>
          <div class="mt-6 max-w-xl quill-content text-justify sm:mt-10">
            <%= raw(@post.body) %>
          </div>
        </div>
        <div class="mt-10 flex">
          <%= link_to posts_path, class: 'text-base font-semibold leading-7 text-ibedec-blue-500' do %>
            Leia mais notícias <span aria-hidden="true">&rarr;</span>
          <% end %>
        </div>
      </div>
      <div class="order-1 relative overflow-hidden rounded-3xl bg-gray-900 px-6 pb-9 pt-64 shadow-2xl lg:order-2 sm:px-12 sm:pt-96 lg:sticky lg:top-4 lg:max-w-lg lg:px-8 lg:pb-8 xl:px-10 xl:pb-10">
        <%= image_tag(url_for(@post.cover_image), class: 'absolute inset-0 h-full w-full object-cover') %>
      </div>
    </div>
  </div>
</div>