config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'static_pages#home'

  get 'inicio' => 'static_pages#home', as: :home
  get 'contato' => 'static_pages#contact', as: :contact
  get 'noticias' => 'posts#index', as: :posts
  get 'noticias/:slug' => 'posts#show', as: :post
  get 'decisoes' => 'judgements#index', as: :judgements
  get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  get 'sobre' => 'static_pages#about', as: :about

  scope path: 'cartilhas-e-manuais' do
    get 'consumidor' => 'static_pages#consumer_content', as: :consumer_content
    get 'construtoras' => 'static_pages#construction_content', as: :construction_content
    get 'previdenciario' => 'static_pages#social_security_content', as: :social_security_content
    get 'sfh-sfi' => 'static_pages#sfh_sfi_content', as: :sfh_sfi_content
  end

  resources :newsletter_subscribers, only: %i[create]

  namespace 'admin' do
    root to: 'posts#index'

    resources :judgements, path: :decisoes
    resources :posts, path: :noticias
  end
end

app/models/judgement.rb
# frozen_string_literal: true

class Judgement < ApplicationRecord
  VALID_SORT_ORDERS = %i[asc desc].freeze
  CATEGORIES = %i[consumer construction sfh_sfi social_security].freeze

  belongs_to :user
  has_one_attached :file

  validates :title, :category, :published_at, :file, presence: true

  scope :sorted_by_date, lambda { |order|
    order = VALID_SORT_ORDERS.find { |sort_order| sort_order.downcase.to_sym == order }

    order("judgements.published_at #{order}")
  }
end

app/controllers/admin/judgements_controller.rb
# frozen_string_literal: true

module Admin
  class JudgementsController < ApplicationController
    load_and_authorize_resource

    def index
      @judgements = Judgement.accessible_by(current_ability).sorted_by_date(:desc).page(params[:page])
    end

    def create
      @judgement.user = current_user

      if @judgement.save
        redirect_to admin_judgements_path, success: 'Decisão criada com sucesso'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @judgement.update(judgement_params)
        redirect_to admin_judgements_path, success: 'Decisão atualizada com sucesso'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @judgement.destroy

      redirect_to admin_judgements_path, success: 'Decisão apagada com sucesso', status: :see_other
    end

    private

    def judgement_params
      params.require(:judgement).permit(:title, :body, :category, :slug, :published_at, :file)
    end
  end
end

app/controllers/judgements_controller.rb
# frozen_string_literal: true

class JudgementsController < ApplicationController
  JUDGEMENTS_PER_PAGE = 6

  def index
    @judgements = Judgement.sorted_by_date(:desc).page(params[:page]).per(JUDGEMENTS_PER_PAGE)
  end
end

app/views/admin/judgements/_form.html.erb
<%= form_with(model: judgement, url: judgement.persisted? ? admin_judgement_path(judgement) : admin_judgements_path, html: { class: 'space-y-6' }) do |form| %>
  <%= render 'shared/form/input', form: form, attribute: :title, kind: :text_field %>
  <%= render 'shared/form/select',
             form: form,
             attribute: :category,
             choices: options_for_select(
               Judgement::CATEGORIES.map { |category| t("activerecord.attributes.judgement.categories.#{category}") }
             ) %>
  <%= render 'shared/form/input', form: form, attribute: :published_at, kind: :date_field %>
  <%= render 'shared/form/file_input', form: form, attribute: :file %>
  <%= render 'shared/form/submit_button', form: form %>
<% end %>

app/views/admin/judgements/edit.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <div class="flex min-h-full flex-col justify-center mt-10 px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-3xl">
      <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
        Atualizar decisão
      </h2>
    </div>

    <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-3xl">
      <div class="bg-white px-4 py-8 sm:px-10">
        <%= render 'form', judgement: @judgement %>
      </div>
    </div>
  </div>
</div>

app/views/admin/judgements/index.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <div class="mx-auto max-w-7xl mt-10 px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-2xl font-semibold leading-6 text-gray-900 sm:text-3xl">
          Decisões
        </h1>
      </div>
      <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
        <%= link_to 'Cadastrar decisão', new_admin_judgement_path, class: 'block rounded-md bg-ibedec-blue-100 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-ibedec-blue-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ibedec-blue-600' %>
      </div>
    </div>
    <div class="mt-8 flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <table class="min-w-full divide-y divide-gray-300">
            <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">
                Título
              </th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                Data de publicação
              </th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Editar</span>
              </th>
            </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
              <% @judgements.each do |judgement| %>
                <tr>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                    <%= judgement.title.truncate(100) %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <%= l(judgement.published_at, format: :long) %>
                  </td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                    <%= link_to 'Editar', edit_admin_judgement_path(judgement), class: 'text-ibedec-blue-600 hover:text-ibedec-blue-600' %>
                  </td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                    <%= link_to 'Apagar', admin_judgement_path(judgement), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Você tem certeza?' }, class: 'text-red-600 hover:text-red-900' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= paginate @judgements %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/judgements/new.html.erb
<div class="pb-16 pt-24 sm:pt-32">
  <div class="flex min-h-full flex-col justify-center mt-10 px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-3xl">
      <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
        Nova decisão
      </h2>
    </div>

    <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-3xl">
      <div class="bg-white px-4 py-8 sm:px-10">
        <%= render 'form', judgement: @judgement %>
      </div>
    </div>
  </div>
</div>