config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'static_pages#home'

  get 'inicio' => 'static_pages#home', as: :home
  get 'contato' => 'static_pages#contact', as: :contact
  get 'noticias' => 'posts#index', as: :posts
  get 'noticias/:slug' => 'posts#show', as: :post
  get 'decisoes' => 'judgements#index', as: :judgements
  get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  get 'sobre' => 'static_pages#about', as: :about

  scope path: 'cartilhas-e-manuais' do
    get 'consumidor' => 'static_pages#consumer_content', as: :consumer_content
    get 'construtoras' => 'static_pages#construction_content', as: :construction_content
    get 'previdenciario' => 'static_pages#social_security_content', as: :social_security_content
    get 'sfh-sfi' => 'static_pages#sfh_sfi_content', as: :sfh_sfi_content
  end

  resources :newsletter_subscribers, only: %i[create]

  namespace 'admin' do
    root to: 'posts#index'

    resources :judgements, path: :decisoes
    resources :posts, path: :noticias
  end
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < ::ApplicationController
    layout 'admin'

    before_action :authenticate_user!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone_number])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def canonical_url
    url = url_for(only_path: false)
    url += '?' if request.query_parameters.any?

    request.query_parameters.each do |key, value|
      url += "#{key}=#{value}"
    end

    url
  end
end

app/views/application/_footer.html.erb
<div class="bg-ibedec-blue-500 sticky top-[100vh] py-16 sm:py-24 lg:py-32">
  <div class="mx-auto grid max-w-7xl grid-cols-1 gap-10 px-6 lg:grid-cols-12 lg:gap-8 lg:px-8">
    <div class="max-w-xl text-3xl font-bold tracking-tight text-white sm:text-4xl lg:col-span-7">
      <h2 class="inline sm:block lg:inline xl:block">Quer receber nossas notícias por email?</h2>
    </div>
    <%= form_with(model: NewsletterSubscriber.new, url: newsletter_subscribers_path, class: 'w-full max-w-md lg:col-span-5 lg:pt-2') do |form| %>
      <div class="flex gap-x-4">
        <label for="email-address" class="sr-only">Email</label>
        <%= form.email_field :email, autocomplete: 'email', placeholder: 'Informe seu email', required: true, class: 'min-w-0 flex-auto rounded-md border-0 bg-white/10 px-3.5 py-2 text-white shadow-sm ring-1 ring-inset ring-white/10 placeholder:text-white/75 focus:ring-2 focus:ring-inset focus:ring-white sm:text-sm sm:leading-6' %>
        <%= form.submit 'Inscrever', class: 'flex-none rounded-md cursor-pointer bg-white px-3.5 py-2.5 text-sm font-semibold text-ibedec-blue-600 shadow-sm hover:bg-ibedec-blue-100 hover:text-ibedec-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white' %>
      </div>
      <p class="mt-4 text-sm leading-6 text-gray-300">
        Leia nossa <%= link_to 'política de privacidade', privacy_policy_path, class: 'font-semibold text-white hover:text-ibedec-yellow-500' %>.
      </p>
    <% end %>
  </div>
</div>

app/views/application/_menu.html.erb
<header data-controller="mobile-menu" class="absolute inset-x-0 top-0 z-50">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <%= link_to root_path, class: '-m-1.5 p-1.5' do %>
        <span class="sr-only">IBEDEC</span>
        <%= vite_image_tag 'images/logo-small.png', class: 'h-16 w-auto rounded-md sm:h-20' %>
      <% end %>
    </div>
    <div class="flex lg:hidden">
      <button data-mobile-menu-target="openButton" data-action="click->mobile-menu#open" type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
        <span class="sr-only">Open main menu</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>
    </div>
    <div class="hidden lg:flex lg:gap-x-12">
      <%= link_to 'Início', root_path, class: "#{request.path == '/' ? 'text-ibedec-blue-300' : 'text-gray-900'} text-sm font-semibold leading-6 py-2" %>
      <%= link_to 'Sobre', about_path, class: "#{request.path == '/sobre' ? 'text-ibedec-blue-300' : 'text-gray-900'} text-sm font-semibold leading-6 py-2" %>
      <%= link_to 'Notícias', posts_path, class: "#{controller_name == 'posts' ? 'text-ibedec-blue-300' : 'text-gray-900'} text-sm font-semibold leading-6 py-2" %>
      <div class="relative inline-block py-2"
           x-data="{ isBookletsOpen: false }"
           @mouseleave = "isBookletsOpen = false">
        <button type="button"
                class="<%= request.path.include?('cartilhas-e-manuais') ? 'text-ibedec-blue-300' : 'text-gray-900' %> inline-flex w-full justify-center items-center text-sm font-semibold leading-6"
                id="menu-button"
                aria-expanded="true"
                aria-haspopup="true"
                @mouseover="isBookletsOpen = true">
          Cartilhas e Manuais
          <%= svg_icon(name: 'caret-down', css_class: '-mr-1 h-5 w-5 mt-0.5 ml-0.5 text-gray-600') %>
        </button>
        <div class="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
             role="menu"
             aria-orientation="vertical"
             aria-labelledby="menu-button"
             tabindex="-1"
             x-cloak
             x-show="isBookletsOpen"
             x-transition:enter="transition ease-out duration-100"
             x-transition:enter-start="transform opacity-0 scale-95"
             x-transition:enter-end="transform opacity-100 scale-100"
             x-transition:leave="transition ease-in duration-75"
             x-transition:leave-start="transform opacity-100 scale-100"
             x-transition:leave-end="transform opacity-0 scale-95">
          <div role="none">
            <%= link_to 'Consumidor', consumer_content_path, class: "block px-4 py-2 text-sm #{current_page?(consumer_content_path) ? 'bg-gray-100 text-gray-900' : 'text-gray-700'}" %>
            <%= link_to 'Construtoras', construction_content_path, class: "block px-4 py-2 text-sm #{current_page?(construction_content_path) ? 'bg-gray-100 text-gray-900' : 'text-gray-700'}" %>
            <%= link_to 'Previdenciário', social_security_content_path, class: "block px-4 py-2 text-sm #{current_page?(social_security_content_path) ? 'bg-gray-100 text-gray-900' : 'text-gray-700'}" %>
            <%= link_to 'SFH e SFI', sfh_sfi_content_path, class: "block px-4 py-2 text-sm #{current_page?(sfh_sfi_content_path) ? 'bg-gray-100 text-gray-900' : 'text-gray-700'}" %>
          </div>
        </div>
      </div>
      <%= link_to 'Decisões', judgements_path, class: "#{controller_name == 'judgements' ? 'text-ibedec-blue-300' : 'text-gray-900'} text-sm font-semibold leading-6 py-2" %>
      <%= link_to 'Contato', contact_path, class: "#{request.path == '/contato' ? 'text-ibedec-blue-300' : 'text-gray-900'} text-sm font-semibold leading-6 py-2" %>
    </div>
  </nav>
  <!-- Mobile menu, show/hide based on menu open state. -->
  <div data-mobile-menu-target="menu" class="lg:hidden" role="dialog" aria-modal="true">
    <!-- Background backdrop, show/hide based on slide-over state. -->
    <div class="fixed inset-0 z-50"></div>
    <div class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
      <div class="flex items-center justify-between sm:justify-end">
        <%= link_to root_path, class: '-m-1.5 p-1.5 sm:invisible' do %>
          <span class="sr-only">IBEDEC</span>
          <%= vite_image_tag 'images/logo-small.png', class: 'h-16 w-auto rounded-md sm:h-20' %>
        <% end %>
        <button data-mobile-menu-target="closeButton" data-action="click->mobile-menu#close" type="button" class="hidden -m-2.5 rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Close menu</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="mt-6 flow-root">
        <div class="-my-6 divide-y divide-gray-500/10">
          <div class="space-y-2 py-6">
            <%= link_to 'Início', root_path, class: "#{request.path == '/' ? 'bg-ibedec-blue-50 text-ibedec-blue-300' : 'text-gray-900'} -mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7" %>
            <%= link_to 'Sobre', about_path, class: "#{request.path == '/sobre' ? 'bg-ibedec-blue-50 text-ibedec-blue-300' : 'text-gray-900'} -mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7" %>
            <%= link_to 'Notícias', posts_path, class: "#{controller_name == 'posts' ? 'bg-ibedec-blue-50 text-ibedec-blue-300' : 'text-gray-900'} -mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7" %>
            <div class="relative block"
                 x-data="{ isBookletsMobileOpen: false }"
                 @click = "isBookletsMobileOpen = !isBookletsMobileOpen">
              <button type="button"
                      @click.outside = "isBookletsMobileOpen = false"
                      class="<%= request.path.include?('cartilhas-e-manuais') ? 'text-ibedec-blue-300' : 'text-gray-900' %> inline-flex justify-center items-center -mx-3 rounded-lg py-2 px-3 text-base font-semibold leading-7"
                      id="menu-button"
                      aria-expanded="true"
                      aria-haspopup="true">
                Cartilhas e Manuais
                <%= svg_icon(name: 'caret-down', css_class: '-mr-1 h-5 w-5 mt-0.5 ml-0.5 text-gray-600') %>
              </button>
              <div class="p-2"
                   role="menu"
                   aria-orientation="vertical"
                   aria-labelledby="menu-button"
                   tabindex="-1"
                   x-cloak
                   x-show="isBookletsMobileOpen"
                   x-transition:enter="transition ease-out duration-100"
                   x-transition:enter-start="transform opacity-0 scale-95"
                   x-transition:enter-end="transform opacity-100 scale-100"
                   x-transition:leave="transition ease-in duration-75"
                   x-transition:leave-start="transform opacity-100 scale-100"
                   x-transition:leave-end="transform opacity-0 scale-95">
                <div role="none">
                  <%= link_to 'Consumidor', consumer_content_path, class: 'block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900' %>
                  <%= link_to 'Construtoras', construction_content_path, class: 'block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900' %>
                  <%= link_to 'Previdenciário', social_security_content_path, class: 'block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900' %>
                  <%= link_to 'SFH e SFI', sfh_sfi_content_path, class: 'block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900' %>
                </div>
              </div>
            </div>
            <%= link_to 'Decisões', judgements_path, class: "#{controller_name == 'judgements' ? 'bg-ibedec-blue-50 text-ibedec-blue-300' : 'text-gray-900'} -mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7" %>
            <%= link_to 'Contato', contact_path, class: "#{request.path == '/contato' ? 'bg-ibedec-blue-50 text-ibedec-blue-300' : 'text-gray-900'} -mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<% if false %>
  <div class="bg-gray-100 text-gray-900 text-gray-700"></div>
<% end %>